KEY_TO_SYM = {
    "ArrowLeft": "Left",
    "ArrowRight": "Right",
    "ArrowUp": "Up",
    "ArrowDown": "Down",
    "BackSpace": "BackSpace",
    "Tab": "Tab",
    "Enter": "Return",
    # 'Shift': 'Shift_L',
    # 'Control': 'Control_L',
    # 'Alt': 'Alt_L',
    "CapsLock": "Caps_Lock",
    "Escape": "Escape",
    " ": "space",
    "PageUp": "Prior",
    "PageDown": "Next",
    "Home": "Home",
    "End": "End",
    "Delete": "Delete",
    "Insert": "Insert",
    "*": "asterisk",
    "+": "plus",
    "|": "bar",
    "-": "minus",
    ".": "period",
    "/": "slash",
    "F1": "F1",
    "F2": "F2",
    "F3": "F3",
    "F4": "F4",
    "F5": "F5",
    "F6": "F6",
    "F7": "F7",
    "F8": "F8",
    "F9": "F9",
    "F10": "F10",
    "F11": "F11",
    "F12": "F12",
}


INTERACTION_THROTTLE = 100
